name: Deploy Next.js App

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: portfolio-website-template
        run: echo "n" | vercel --token $VERCEL_TOKEN --prod --scope $VERCEL_ORG_ID --build-env VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID
